version: '3.8'

services:
  rails-app:
    image: iris-system
    # container_name: rails-app
    build: .
    # ports:
    #   - 3000:3000
    depends_on:
      - db
    networks:
      - app-network
    
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: irisdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty
    networks:
      - app-network
    
  Nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - rails-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
